require('core.plugin_config.theme')
require('core.plugin_config.tree')
require('core.plugin_config.lualine')
require('core.plugin_config.telescope')
require('core.plugin_config.autocomplete')
require('core.plugin_config.treesitter')
require('core.plugin_config.lsp')
